### ISSUE TITLE
如何能单独使用主题

### ISSUE THREAD

**Issue by chinalijinglun** [o2team/o2team.github.io#19]
你好，主题直接放进theme里会报错，hexo 3.2.2， nodejs 5.4.0.

是还需要npm什么吗？

报错信息：

Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (D:\WWW\hexo\themes\lattice\scripts\helpers.js:128:44)

    at wrapper (D:\WWW\hexo\node_modules\.4.17.4@lodash\lodash.js:4968:19)
    at Object.eval [as tpl] (eval at <anonymous> (D:\WWW\hexo\node_modules\.1.4.
2@swig\lib\swig.js:498:13), <anonymous>:16:143)
    at compiled (D:\WWW\hexo\node_modules\.1.4.2@swig\lib\swig.js:619:18)
    at _compiledSync (D:\WWW\hexo\node_modules\.3.2.2@hexo\lib\theme\view.js:122
:20)
    at View.renderSync (D:\WWW\hexo\node_modules\.3.2.2@hexo\lib\theme\view.js:5
0:21)
    at Object.partial (D:\WWW\hexo\node_modules\.3.2.2@hexo\lib\plugins\helper\p
artial.js:42:17)
    at wrapper (D:\WWW\hexo\node_modules\.4.17.4@lodash\lodash.js:4968:19)
    at Object.eval [as tpl] (eval at <anonymous> (D:\WWW\hexo\node_modules\.1.4.
2@swig\lib\swig.js:498:13), <anonymous>:15:119)
    at compiled (D:\WWW\hexo\node_modules\.1.4.2@swig\lib\swig.js:619:18)
    at _compiled (D:\WWW\hexo\node_modules\.3.2.2@hexo\lib\theme\view.js:127:30)

    at View.render (D:\WWW\hexo\node_modules\.3.2.2@hexo\lib\theme\view.js:29:15
)
    at D:\WWW\hexo\node_modules\.3.2.2@hexo\lib\hexo\index.js:387:25
    at tryCatcher (D:\WWW\hexo\node_modules\.3.4.7@bluebird\js\release\util.js:1
6:23)
    at D:\WWW\hexo\node_modules\.3.4.7@bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\WWW\hexo\node_modules\.3.2.2@hexo\lib\hexo\router.j
s:134:3)
    at RouteStream.Readable.read (_stream_readable.js:328:10)
    at resume_ (_stream_readable.js:718:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

**Comment by mamboer** [comment]
这个主题 `lattice` 是定制主题，没有梳理成通用的hexo主题，你可以做以下尝试：

1. 参考 `package.json` 补全依赖包
2. 确保 `source` 目录下的 `_data` 目录需要和我们这个项目的一致。

如果还不行的话，建议你拷贝讲整个仓库，将 `_posts` 目录下的内容替换成为你的内容即可。

**Comment by chinalijinglun** [comment]
感谢。
